(require '[shi.api.keystone :as ks])
(require '[shi.api.glance :as gl])
(require '[shi.api.nova :as nova])
(require '[shi.environment.config :as cfg])
(require '[clojure.pprint :as cpp])
(require '[clojure.reflect :as refl])
(require '[cheshire.core :as ches])
(require '[org.httpkit.client :as http])

(def cred3 (ks/make-creds-v3 :userid (cfg/config :user-name)
                             :auth-url (cfg/config :auth-url)
                             :authmethod "password"
                             :secret (cfg/config :user-pass)))
(def auth (ks/authorize cred3))
(def catalog (ks/get-catalog auth))

(let [catalog (ks/get-catalog auth)
      images (gl/image-list auth)
      keystone (ks/get-service [:keystone] catalog)
      {:keys [url token]} (ks/get-rest-basics auth :keystone)
      ]
  (println "Response: " auth)
  (println "================================")
  (println "Catalog: " catalog)
  (println "================================")
  (println "Token: " token)
  (println "================================")
  (println "Keystone: " (first keystone))
  (println "================================")
  (cpp/pprint images)
  (println "================================")
  (println "Url:" url))

(let [keystone (ks/!get-service-info auth :keystone)
      token (:token keystone)
      v2url (:url keystone)
      url (clojure.string/replace v2url #"v2.0" "v3")]
  {:url url :token token})